# Generated by Django 4.1.7 on 2023-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiplugPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('favourite', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
